import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerSubtitle: {
    fontSize: 16,
    color: "rgba(255,255,255,0.8)",
    marginTop: 4,
  },
  toastContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  successToast: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D9D9D9",
    borderRadius: 4,
    paddingHorizontal: 8,
    height: 36,
    gap: 6,
  },
  checkCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#962DFF",
    justifyContent: "center",
    alignItems: "center",
  },
  successToastText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#000000",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingTop: 24,
  },
  levelCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  levelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  levelLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  foxEmoji: {
    fontSize: 36,
  },
  levelTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
  },
  levelName: {
    fontSize: 14,
    color: "#6B7280",
  },
  xpText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3B5BDB",
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#3B5BDB",
    borderRadius: 4,
  },
  xpLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  xpLabel: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
  },
  addButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#3B5BDB",
    justifyContent: "center",
    alignItems: "center",
  },
  goalItem: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  goalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  goalLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  goalIcon: {
    fontSize: 28,
  },
  goalName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
  },
  goalProgress: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  goalPercentage: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2E47F9",
  },
  goalProgressBarContainer: {
    height: 6,
    backgroundColor: "#AFAFAF",
    borderRadius: 3,
    overflow: "hidden",
  },
  goalProgressBar: {
    height: "100%",
    backgroundColor: "rgba(42, 58, 230, 0.69)",
    borderRadius: 3,
  },
  goalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 12,
  },
  goalRemainingLabel: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  goalRemainingValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#3B5BDB",
  },
  budgetItem: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  budgetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  budgetLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  budgetIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  budgetName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
  },
  budgetProgress: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  budgetLimit: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3B5BDB",
  },
  budgetProgressBarContainer: {
    height: 6,
    backgroundColor: "#AFAFAF",
    borderRadius: 3,
    overflow: "hidden",
  },
  budgetProgressBar: {
    height: "100%",
    backgroundColor: "rgba(42, 58, 230, 0.69)",
    borderRadius: 3,
  },
  budgetProgressBarOver: {
    backgroundColor: "#EF4444",
  },
  budgetProgressOver: {
    color: "#EF4444",
  },
  budgetLimitOver: {
    color: "#EF4444",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#D1D5DB",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 24,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 8,
  },
  nameInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    marginBottom: 16,
  },
  emojiButton: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRightWidth: 1,
    borderRightColor: "#E5E7EB",
  },
  emojiButtonText: {
    fontSize: 24,
  },
  nameInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#000000",
    outlineStyle: "none",
  } as any,
  emojiPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 8,
    marginBottom: 16,
    gap: 8,
  },
  emojiOption: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  emojiOptionText: {
    fontSize: 24,
  },
  modalInput: {
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#000000",
    marginBottom: 16,
    outlineStyle: "none",
  } as any,
  calculationText: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 24,
  },
  calculationBold: {
    fontWeight: "700",
    color: "#000000",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  cancelButton: {
    backgroundColor: "#9CA3AF",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 28,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  createButton: {
    backgroundColor: "#7340FE",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 28,
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 12,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 8,
    marginBottom: 16,
    gap: 8,
  },
  categoryItem: {
    width: "22%",
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 12,
  },
  categoryItemSelected: {
    backgroundColor: "#E0C6FD",
  },
  categoryIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  categoryName: {
    fontSize: 10,
    color: "#374151",
    textAlign: "center",
  },
  budgetRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  budgetDetailModal: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: "80%",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  budgetDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 24,
  },
  budgetDetailTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#000000",
  },
  budgetDetailSubtitle: {
    fontSize: 14,
    color: "#6B7280",
  },
  transactionsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 12,
  },
  transactionsList: {
    maxHeight: 300,
  },
  emptyTransactions: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyTransactionsText: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 12,
  },
  transactionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  transactionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  transactionIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  transactionName: {
    fontSize: 14,
    fontWeight: "500",
    color: "#000000",
  },
  transactionDate: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#10B981",
  },
  transactionAmountNegative: {
    color: "#EF4444",
  },
  closeDetailButton: {
    backgroundColor: "#7340FE",
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 20,
  },
  closeDetailButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
