import { BorderRadius, Spacing } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerSubtitle: {
    fontSize: 16,
    color: "rgba(255,255,255,0.8)",
    marginTop: 4,
  },
  toggleContainer: {
    flexDirection: "row",
    marginTop: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 25,
    padding: 4,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 22,
  },
  toggleButtonActive: {
    backgroundColor: "#FFFFFF",
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255,255,255,0.8)",
  },
  toggleButtonTextActive: {
    color: "#3B5BDB",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
    marginBottom: 12,
  },
  filterBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
  },
  filterBadgeActive: {
    backgroundColor: "#EDE9FE",
    borderWidth: 1,
    borderColor: "#7340fd",
  },
  filterBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  filterBadgeTextActive: {
    color: "#7340fd",
  },
  tabsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "#3B5BDB",
    borderColor: "#3B5BDB",
  },
  tabButtonText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#6B7280",
    textAlign: "center",
  },
  tabButtonTextActive: {
    color: "#FFFFFF",
  },
  chartCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  chartWrapper: {
    width: 220,
    height: 220,
    justifyContent: "center",
    alignItems: "center",
  },
  chartCenter: {
    position: "absolute",
    alignItems: "center",
  },
  chartAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
  },
  chartLabel: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 4,
  },
  chartPercentage: {
    fontSize: 12,
    color: "#3B5BDB",
    fontWeight: "600",
    marginTop: 2,
  },
  kategorienGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 24,
    width: "100%",
  },
  kategorieItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "50%",
    marginBottom: 16,
    gap: 10,
    padding: 8,
    margin: -8,
    borderRadius: 8,
  },
  kategorieItemSelected: {
    backgroundColor: "rgba(59, 91, 219, 0.1)",
    margin: 0,
    marginBottom: 8,
    width: "50%",
  },
  kategorieDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  kategorieName: {
    fontSize: 14,
    fontWeight: "500",
    color: "#000000",
  },
  kategorieBetrag: {
    fontSize: 14,
    fontWeight: "600",
    color: "#3B5BDB",
    marginTop: 2,
  },
  pagerView: {
    flex: 1,
    minHeight: 550,
  },
  pagerPage: {
    flex: 1,
  },
  incomeExpensesContainer: {
    gap: 16,
  },
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  summaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusPositive: {
    backgroundColor: "#ECFDF5",
  },
  statusNegative: {
    backgroundColor: "#FEF2F2",
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  statusTextPositive: {
    color: "#059669",
  },
  statusTextNegative: {
    color: "#DC2626",
  },
  barSection: {
    marginBottom: 16,
  },
  barRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  barLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  barIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  barLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#374151",
  },
  barValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000000",
  },
  barTrack: {
    height: 12,
    backgroundColor: "#F3F4F6",
    borderRadius: 6,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 6,
  },
  barFillIncome: {
    backgroundColor: "#22C55E",
  },
  barFillExpenses: {
    backgroundColor: "#EF4444",
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 16,
  },
  differenceSection: {
    gap: 8,
  },
  differenceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  differenceLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
  },
  differenceValue: {
    fontSize: 20,
    fontWeight: "700",
  },
  differencePositive: {
    color: "#059669",
  },
  differenceNegative: {
    color: "#DC2626",
  },
  savingsLabel: {
    fontSize: 14,
    color: "#6B7280",
  },
  savingsValue: {
    fontSize: 16,
    fontWeight: "600",
  },
  tipsCard: {
    backgroundColor: "#FFFBEB",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  tipsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  tipsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#92400E",
  },
  tipsText: {
    fontSize: 14,
    color: "#78350F",
    lineHeight: 20,
  },
  trendContainer: {
    gap: 16,
  },
  trendHeader: {
    marginBottom: 16,
  },
  trendSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 4,
  },
  trendStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  trendStat: {
    flex: 1,
  },
  trendStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: "#E5E7EB",
    marginHorizontal: 16,
  },
  trendStatLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 4,
  },
  trendStatValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
  },
  trendPositive: {
    color: "#059669",
  },
  trendNegative: {
    color: "#DC2626",
  },
  chartContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  trendChartSelectedAmount: {
    backgroundColor: "#5B6BBE",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: "center",
    marginBottom: 12,
  },
  trendChartSelectedAmountText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  trendChartBars: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 130,
    width: "100%",
  },
  trendBarContainer: {
    alignItems: "center",
    flex: 1,
  },
  trendBarWrapper: {
    height: 100,
    justifyContent: "flex-end",
  },
  trendBar: {
    width: 28,
    borderRadius: 8,
  },
  trendBarZero: {
    width: 20,
    borderRadius: 6,
  },
  trendBarSelected: {
    width: 32,
  },
  trendBarDimmed: {
    opacity: 0.5,
  },
  trendBarLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 8,
  },
  trendBarLabelSelected: {
    color: "#5B6BBE",
    fontWeight: "600",
  },
  trendHint: {
    fontSize: 12,
    color: "#9CA3AF",
    textAlign: "center",
    marginBottom: 12,
  },
  trendChangeRow: {
    alignItems: "center",
  },
  changeIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  changePositive: {
    backgroundColor: "#ECFDF5",
  },
  changeNegative: {
    backgroundColor: "#FEF2F2",
  },
  changeText: {
    fontSize: 13,
    fontWeight: "500",
  },
  changeTextPositive: {
    color: "#059669",
  },
  changeTextNegative: {
    color: "#DC2626",
  },
  insightCards: {
    flexDirection: "row",
    gap: 12,
  },
  insightCard: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 2,
    borderColor: "transparent",
  },
  insightCardSelected: {
    borderColor: "#3B5BDB",
    backgroundColor: "#F0F4FF",
  },
  insightIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  insightContent: {
    flex: 1,
  },
  insightLabel: {
    fontSize: 11,
    color: "#6B7280",
    marginBottom: 2,
  },
  insightValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 12,
    minHeight: 350,
  },
  modalScrollView: {
    maxHeight: "100%",
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#D1D5DB",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 32,
  },
  modalDoneButton: {
    backgroundColor: "#7340fd",
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: "auto",
  },
  modalDoneButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  incomeSummaryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    marginBottom: Spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  incomeSummaryIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  incomeSummaryContent: {
    flex: 1,
  },
  incomeSummaryLabel: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 4,
  },
  incomeSummaryAmount: {
    fontSize: 28,
    fontWeight: "700",
    color: "#10B981",
  },
  addIncomeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F0FF",
    alignItems: "center",
    justifyContent: "center",
  },
  incomeSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginBottom: Spacing.md,
  },
  incomeEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing["2xl"],
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.lg,
  },
  incomeEmptyText: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: Spacing.md,
    marginBottom: Spacing.lg,
  },
  incomeEmptyButton: {
    backgroundColor: "#7340fd",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  incomeEmptyButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  incomeItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
  },
  incomeLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  incomeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  incomeType: {
    fontSize: 15,
    fontWeight: "500",
    color: "#111827",
  },
  incomeFrequency: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  incomeRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  incomeAmount: {
    fontSize: 16,
    fontWeight: "600",
    color: "#10B981",
  },
  deleteConfirm: {
    backgroundColor: "#FEF2F2",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginTop: -Spacing.sm + 4,
    marginBottom: Spacing.sm,
  },
  deleteConfirmText: {
    fontSize: 14,
    color: "#991B1B",
    marginBottom: Spacing.sm,
  },
  deleteActions: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  cancelDeleteBtn: {
    flex: 1,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },
  cancelDeleteText: {
    fontSize: 14,
    color: "#6B7280",
  },
  confirmDeleteBtn: {
    flex: 1,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: "#EF4444",
    alignItems: "center",
  },
  confirmDeleteText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  incomeTipCard: {
    backgroundColor: "#F3F0FF",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.xl,
  },
  incomeTipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  incomeTipTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7340fd",
  },
  incomeTipText: {
    fontSize: 13,
    color: "#4C1D95",
    lineHeight: 18,
  },
  incomeModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  incomeModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: Spacing.lg,
  },
  incomeModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.lg,
  },
  incomeModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
  },
  incomeModalLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#374151",
    marginBottom: Spacing.sm,
    marginTop: Spacing.md,
  },
  incomeTypeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  incomeTypeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "transparent",
  },
  incomeTypeButtonSelected: {
    backgroundColor: "#F3F0FF",
    borderColor: "#7340fd",
  },
  incomeTypeButtonText: {
    fontSize: 13,
    color: "#6B7280",
  },
  incomeTypeButtonTextSelected: {
    color: "#7340fd",
    fontWeight: "500",
  },
  customTypeContainer: {
    marginTop: Spacing.sm,
  },
  incomeTextInput: {
    backgroundColor: "#F9FAFB",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    fontSize: 16,
    color: "#111827",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    outlineStyle: "none",
  } as any,
  incomeAmountInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: Spacing.md,
  },
  incomeCurrencySymbol: {
    fontSize: 18,
    color: "#6B7280",
    marginRight: Spacing.xs,
  },
  incomeAmountInput: {
    flex: 1,
    paddingVertical: Spacing.md,
    fontSize: 18,
    color: "#111827",
    outlineStyle: "none",
  } as any,
  incomeSaveButton: {
    backgroundColor: "#7340fd",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    marginTop: Spacing.xl,
  },
  incomeSaveButtonDisabled: {
    backgroundColor: "#D1D5DB",
  },
  incomeSaveButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  fixkostenContainer: {
    flex: 1,
  },
  expenseSummaryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    marginBottom: Spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  expenseSummaryIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  expenseSummaryContent: {
    flex: 1,
  },
  expenseSummaryLabel: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 4,
  },
  expenseSummaryAmount: {
    fontSize: 28,
    fontWeight: "700",
    color: "#EF4444",
  },
  addExpenseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F0FF",
    alignItems: "center",
    justifyContent: "center",
  },
  expenseSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginBottom: Spacing.md,
  },
  expenseEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing["2xl"],
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.lg,
  },
  expenseEmptyText: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: Spacing.md,
    marginBottom: Spacing.lg,
  },
  expenseEmptyButton: {
    backgroundColor: "#EF4444",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  expenseEmptyButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  expenseItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
  },
  expenseLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  expenseIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  expenseType: {
    fontSize: 15,
    fontWeight: "500",
    color: "#111827",
  },
  expenseFrequency: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  expenseRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  expenseAmount: {
    fontSize: 16,
    fontWeight: "600",
    color: "#EF4444",
  },
  expenseTipCard: {
    backgroundColor: "#FEF2F2",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.xl,
  },
  expenseTipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  expenseTipTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#EF4444",
  },
  expenseTipText: {
    fontSize: 13,
    color: "#991B1B",
    lineHeight: 18,
  },
  expenseTypeButtonSelected: {
    backgroundColor: "#FEF2F2",
    borderColor: "#EF4444",
  },
  expenseTypeButtonTextSelected: {
    color: "#EF4444",
    fontWeight: "500",
  },
  expenseSaveButton: {
    backgroundColor: "#EF4444",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    marginTop: Spacing.xl,
  },
});
